version: '3'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: gerenciador-api
    ports:
      - 4000:4000
    restart: always
    tty: true
    networks:
      - api-gerenciador
    volumes:
      - .:/home/node/app
  db:
    image: mongo:4.4.1
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    tty: true
    networks:
      - api-gerenciador

networks:
   api-gerenciador:

