FROM node:16-alpine

WORKDIR /home/node/app

RUN apk add --no-cache   bash   git   curl

RUN yarn global add @nestjs/cli

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build

ENTRYPOINT [ "yarn", "start:dev" ]

USER node

EXPOSE 3000
